---

name: Publish

on:
  push:
    branches:
      - master

jobs:
  Dockerhub:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: docker build -t system76/tweetflood -f Dockerfile-production .

      - name: Upload
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker push system76/tweetflood:latest
